name: document_scanner_flutter
description: A android & ios document scanner & auto detector plugin for flutter.
version: 0.2.6
homepage: https://github.com/ishaquehassan/document_scanner_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  pdf: 3.10.1
  photo_view: ^0.14.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.document.scanner.flutter.document_scanner_flutter
        pluginClass: DocumentScannerFlutterPlugin
      ios:
        pluginClass: DocumentScannerFlutterPlugin
